'use client';
import { useState } from 'react';
import { adminApi, buttonClass, inputClass } from './api';
type ReturnCase = { id: string; status: string; reason: string; units: number; note: string; resolution: string; stockReceived: boolean; version: number; createdAt: string };
export default function OrderReturns({ reference, totalQuantity, items, refresh }: { reference: string; totalQuantity: number; items: ReturnCase[]; refresh: () => void }) {
 const [busy, setBusy] = useState(false); const [error, setError] = useState('');
 const create = async (form: HTMLFormElement) => { setBusy(true); setError(''); try { const data = new FormData(form); await adminApi(`/orders/${reference}/returns`, { reason: data.get('reason'), units: Number(data.get('units')), note: data.get('note') }); form.reset(); refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save return.'); } finally { setBusy(false); } };
 const update = async (form: HTMLFormElement, item: ReturnCase) => { setBusy(true); setError(''); try { const data = new FormData(form); await adminApi(`/returns/${item.id}`, { version: item.version, status: data.get('status'), resolution: data.get('resolution'), stockReceived: data.get('stockReceived') === 'on' }, 'PATCH'); refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update return.'); } finally { setBusy(false); } };
 return <section className="space-y-4 rounded-xl border border-neutral-200 bg-white p-5"><h2 className="text-lg font-bold">Returns and replacements</h2><p className="text-sm text-neutral-600">Record a case before issuing a refund or replacing goods. Physical stock is restored only through an explicit inventory adjustment after receipt.</p>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<form className="grid gap-3" onSubmit={(e) => { e.preventDefault(); void create(e.currentTarget); }}><input name="reason" required maxLength={1000} placeholder="Reason for return or replacement" className={inputClass}/><input name="units" type="number" required min="1" max={totalQuantity} placeholder="Units affected" className={inputClass}/><textarea name="note" maxLength={2000} placeholder="Internal note (optional)" className={inputClass}/><button disabled={busy} className={buttonClass}>{busy ? 'Saving...' : 'Open return case'}</button></form><ul className="space-y-3">{items.map((item) => <li key={item.id} className="border-t pt-3 text-sm"><strong className="capitalize">{item.status.toLowerCase()}</strong> · {item.units} units<p>{item.reason}</p><form className="mt-3 grid gap-2" onSubmit={(e) => { e.preventDefault(); void update(e.currentTarget, item); }}><select name="status" defaultValue={item.status} className={inputClass}>{['REQUESTED','APPROVED','RECEIVED','REFUNDED','REPLACED','CLOSED','REJECTED'].map((status) => <option key={status}>{status}</option>)}</select><input name="resolution" defaultValue={item.resolution} maxLength={2000} placeholder="Resolution / staff record" className={inputClass}/><label className="text-xs"><input name="stockReceived" type="checkbox" defaultChecked={item.stockReceived}/> Physically received and checked</label><button disabled={busy} className={buttonClass}>Update return</button></form><p className="text-xs text-neutral-500">{new Date(item.createdAt).toLocaleString()}</p></li>)}</ul></section>;
}
